### ISSUE TITLE
[NEW] Linux bridge configuration support for virtual networks

### ISSUE THREAD

**Issue by IceManGreen** [ThalesGroup/freyja#1]
**Is your feature request related to a problem? Please describe.**
When a new network is created, you cannot chose what bridge it will use and is bound to libvirt's `virbr0` bridge by default.
This is inconvenient in some cases where an external DHCP (other than the libvirt's internal dhcp) is related to another bridge (and so another host interface) and has to be used for new VMs IPs management.

**Describe the solution you'd like**
A new configuration for Freyja where a bridge can be OPTIONALLY configured for a network. Default behavior will attach the new network to `virbr0`. 

**Additional context**
Actual behavior :

```sh
freyja network info ctrl-plane-test
ctrl-plane-test:
  Active: 'yes'
  Autostart: 'yes'
  Bridge: virbr0  # SHOULD BE chosen by configuration, or default
  Name: ctrl-plane-test
  Persistent: 'yes'
  UUID: 1dd6a6b4-2b3b-46e1-acf3-6051bfd023c1
```

New conf proposition :

```yaml
---
version: "v0.1.0-beta"
hosts:
  - image: "$HOME/Images/debian11"
    os: "debian11"
    hostname: "freyja" 
    networks:
      - name: "ctrl-plane-test"
        bridge: "br-ctrl-plane"
        address: "52:54:02:aa:aa:bb"
```
