### ISSUE TITLE
[BUG] Multiple files provisioning not working

### ISSUE THREAD

**Issue by IceManGreen** [ThalesGroup/freyja#11]
**Describe the bug**
When multiple files are configured for provisioning, only the first file appears in the final guest's file system.

**To Reproduce**

Configure a machine like :

```yaml
#https://cloud.debian.org/images/cloud/bullseye/latest/debian-11-generic-amd64.qcow2
version: "v0.1.0-beta"
hosts:
  - hostname: "test"
    image: "$HOME/Images/debian11"
    os: "debian11"
    users:
      - keys: ["$HOME/.ssh/id_ed25519.pub"]
        username: bob
    write-files:
      - source: "$HOME/script1.sh"
        destination: "/usr/local/bin/script1.sh"
        permissions: "0770"
        owner: "bob:bob"
      - source: "$HOME/script2.sh"
        destination: "/usr/local/bin/script2.sh"
        permissions: "0770"
        owner: "bob:bob"
```

connect to the guest with ssh ->  the second file `/usr/local/bin/script2.sh/` does not exist

**Expected behavior**
`/usr/local/bin/script2.sh/` should be present.

**Desktop (please complete the following information):**
 - OS: ubuntu22.04
 - Version : freyja v0.1.0-beta
