### ISSUE TITLE
[NEW] Mutliple disk mount for multi partitioning in configuration

### ISSUE THREAD

**Issue by IceManGreen** [ThalesGroup/freyja#3]
**Is your feature request related to a problem? Please describe.**
Actually, I cannot mount multiple partition on a virtual guest without creating it first, then using libvirt and ssh commands to manually mount additional disks and pools.

**Describe the solution you'd like**
I would like a concise configuration to mount additional partitions at boot and keep it easy.
The current configuration :

```yaml
hosts:
    # 'disk' is optional
  - disk: 20
```

Should be replaced with :

```yaml
hosts:
    # 'disks' will be optional
    # default behavior will mount the sysroot on '/' with 30GB 
  - disks:
      # 'sysroot' is optional
      # default behavior will mount the sysroot on '/' with 30GB 
      sysroot:
        size: 30
      # 'additional' will be optional
      additional: 
          # 'size' is mandatory for additional disks
        - size: 30
          # optional: the disk mounted on the filesystem will be accessed with read-only permissions
          read-only: true
```

The former configuration should create 3 partitions: 
- 1 sysroot partition on '/' with 20GB
- 1 additional disk on '/dev/sda1' with 10GB
- 1 additional disk on '/dev/sda2' with 15GB

Technically, simple configuration will still be possible because 'disks' remains optional.
Still, without additional disks, the configuration remains simple :

```yaml
hosts:
  - disks:
      sysroot:
        size: 30
```
